esphome:
  name: espcamera
  platform: ESP32
  board: esp32cam

wifi: !include wifi.yml

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: !include password.yml

ota:
  password: !include password.yml

captive_portal:

# Camera
esp32_camera:
  name: ESP32 Camera
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO17, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15
  resolution: 640x480
  jpeg_quality: 10